### ISSUE TITLE
Add support for the PyTorch Custom model into dstoolkit

### ISSUE THREAD

**Issue by sweanan** [microsoft/dstoolkit-mlops-v2#127]
Description:

DS Toolkit currently has samples for MLFlow model, in case of integrating the custom models, there are changes needed to integrate that into dstoolkit. Add support for this with a general Pytorch custom models

Acceptance criteria:

- PYTorch custom model samples are added to the dstookit

**Comment by vilcek** [comment]
The idea is to integrate an example of a custom Gen AI model. We are suggesting adding an example using a model from Hugging Face Transformers library, which provides access to hundreds of models for NLP, computer vision, audio, and others, through a common API. That will make this new example potentially reusable across many use cases.

**Comment by fysheets** [comment]
Propose closing this issue in favor for https://github.com/microsoft/dstoolkit-mlops-v2/issues/151
