### ISSUE TITLE
Improve VSCode Debug Tasks

### ISSUE THREAD

**Issue by jjordonm** [microsoft/dstoolkit-mlops-v2#140]
Contribute VSCode Debug Tasks to the existing samples, promoting a better dev experience 

- The VSCode Debug Tasks should be added to the existing samples repository
- The contributed Debug Tasks should be well-documented, including clear instructions on how to use them.
- The Debug Tasks should be tested to ensure they work correctly with the existing samples.

**Comment by agonzalez2014** [comment]
This GH issue is well suited for @jjordonm to own
