### ISSUE TITLE
Ability for CI/CD Pipelines to cancel AML Pipelines

### ISSUE THREAD

**Issue by kottofy** [microsoft/dstoolkit-mlops-v2#144]
If a CI/CD Pipeline is cancelled, it leave the AML pipeline running. It would be nice to have a `finally` task so that if the CI/CD pipeline is cancelled, then the AML Pipeline is cancelled. This would reduce cost and resource utilization in AML.

**Comment by agonzalez2014** [comment]
This story is well suited for @jjordonm to own
